### ISSUE TITLE
Not work in blender 3.3.1

### ISSUE THREAD

**Issue by atticus-lv** [mmmrqs/bl_ui_widgets#2] opened 2022-09-25 06:52 UTC
call from f3, the panel show for just one second and gone

**Comment by atticus-lv** [comment] 2022-09-25 06:55
https://user-images.githubusercontent.com/64118610/192132012-c2650e99-7e4c-4473-a3f2-5f9ccb1aca9c.mp4

**Comment by mmmrqs** [comment] 2022-09-25 15:50
> call from f3, the panel show for just one second and gone

Thanks for the issue report.  I verified that this is an existing issue that may happen also when using older Blender releases.  I am currently working on a fix for this issue and I must have it done in a week or so.  Please come back in a few days to check if it available for you to download.

**Comment by atticus-lv** [comment] 2022-09-25 16:53
Thanks for your wonderful work~

**Comment by mmmrqs** [comment] 2022-09-27 22:31
> Thanks for your wonderful work~

Hi atticus-lv,

I have just uploaded a new release with the fix for opening the floating panel from Blender's F3 menu.  I made other improvements too, so that it behaves better when user switches between different views/areas and for QuadView display mode.  

In fact, I had never thought of this panel to be opened by any place other then Blender's side-panel (N-Panel). You will need to take care when opening it from F3 because I do not know how to prevent multiple instances of the panel to get opened by the user. You may want to come up with some way to give the user an option to close (terminate) the floating panel, otherwise the user will end up with multiple instances running at the same time and that may cause issues to Blender.  I plan to research a way in that the panel itself can identify when there is an instance of it already running and then prevent it from opening another instance, however I do not have any estimate on when (and if) this feature will get available.

Please find the updated release at:  
[https://github.com/mmmrqs/bl_ui_widgets/releases/tag/1.0.3](https://github.com/mmmrqs/bl_ui_widgets/releases/tag/1.0.3)

Thanks.

**Comment by atticus-lv** [comment] 2022-09-28 05:28
Great！I will check it later.
To checking there is already an instance, I think we can use a global variable to store it (store the area, too). Then use a handle to poll if area is destory / a panel is create. 
I use this method to ensure a blender popup window is created/destory in my old addon

**Comment by mmmrqs** [comment] 2022-09-29 00:20
> Great！I will check it later. To checking there is already an instance, I think we can use a global variable to store it (store the area, too). Then use a handle to poll if area is destory / a panel is create. I use this method to ensure a blender popup window is created/destory in my old addon

Thank you for the idea, it worked fine.  I've implemented it already and drafted a new release.  Also took the opportunity to fix one remaining issue.  Please check it at:  [https://github.com/mmmrqs/bl_ui_widgets/releases/tag/1.0.4](https://github.com/mmmrqs/bl_ui_widgets/releases/tag/1.0.4)

- Added some logic that prevents the panel to be opened in multiple simultaneous instances.
- Fixed issue with a 'context is incorrect' situation that would be caused by user calling 'Set_Demo_Panel' repeatedly and too fast.

**Comment by atticus-lv** [comment] 2022-10-09 08:34
Just back from holiday. I will try the latest version asap. : )

**Comment by atticus-lv** [comment] 2022-10-09 11:46
find an other problem. when set the value to 2, some btn gone.

https://user-images.githubusercontent.com/64118610/194755140-ac1011b3-6c9e-4e3b-bcec-9a4bb9a46226.mp4

**Comment by mmmrqs** [comment] 2022-10-09 15:55
> find an other problem. when set the value to 2, some btn gone.
> 
>  2022-10-09.19-45-23.mp4

Hi atticus-lv.   I've tried to recreate the issue here, using Blender 3.1.1 and doing exactly like you did but it worked fine for me and I did not see the issue.  Please open Blender's log screen by clicking on Blender's menu:  Windows --> "Toggle System Console" and repeat the steps that caused the issue.  After you type value 2 and the other button disappear, take a look at the System Console window and send me a print screen of it.  What must be happening is some function error after the value is entered, and I need to know which line in the code and what is the error message reported in Blender.

Thanks.

**Comment by atticus-lv** [comment] 2022-10-17 17:58
seems to be a blender bug in 3.4, when I back to 3.3.1, it work well

**Closed** 2022-11-05 17:21 UTC
